[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  VITE_RESEND_API_KEY = "${VITE_RESEND_API_KEY}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
